### ISSUE TITLE
Write user stories

### ISSUE THREAD

**Issue by Zyranix** [hpi-swa-teaching/MorphicAPIExplorer#13]
Until Sat. 1.5., write at least 3 medium-sized User Stories
- [x] first user story
- [x] second user story
- [x] third user story
