### ISSUE TITLE
Combining different categories

### ISSUE THREAD

**Issue by Zyranix** [hpi-swa-teaching/MorphicAPIExplorer#14]
**[13 Hasso Credits]**
As a user I want to be able to combine different categories and keep settings of another category via a list of morphs integrated into the left side panel to see how attributes influence each other

**Comment by Zyranix** [comment]
**Tasks:**
- [ ] enhance functionality of createDefaultMorphBox to support multiple morphs
- [ ] update MEXCategorie instantiation in Overview
- [ ] make morphs clickable/selectable
- [ ] make morphs saveable
