### ISSUE TITLE
Show dependencies between methods

### ISSUE THREAD

**Issue by Zyranix** [hpi-swa-teaching/MorphicAPIExplorer#15]
**[8 Hasso Credits]**
As a user I want to see an icon next to selected methods indicating dependencies on other methods via hover-tooltip in order to more easily understand the way morph attributes work together.

**Comment by taminob** [comment]
**Tasks:**
- [x] MEXToolOverView on class side: add dependencies to category creation methods
- [x] MEXMethod: add dependency list
- [x] add icon with hover function to highlight all dependencies

**Comment by Zyranix** [comment]
not finished in time; we're now trying to get a good overview over the missing parts in the ToolBuilder architecture and as an optimistic goal try to finish this feature until the next Sprint Meeting

**Comment by Zyranix** [comment]
core structure now works; we still need to add tests and some refactoring and polishing

**Comment by Zyranix** [comment]
**[+3 Hasso Credits]**
As a user I want to emphasize methods that are dependent on the currently hovered method via background highlighting and an icon to its left in order to more easily understand the way morph attributes work together.

**Comment by Zyranix** [comment]
- [x] write Tests
- [x] talk with Patrick
- [x] rewrite code for emphasizing actual entry
