### ISSUE TITLE
First preparations for presentation

### ISSUE THREAD

**Issue by Zyranix** [hpi-swa-teaching/MorphicAPIExplorer#34]
- [x] rework architecture (Sina & Morpheus)
- [x] find material collective codeownership (Tamino & Paula)
- [x] create project metrics (Kathrin & Paul)
